/**
 * Cody Proactive — Type Definitions
 *
 * Inspired by:
 * - Hermes Agent's sleep-time compute (async memory management)
 * - OpenClaw's always-on agent pattern (persistent background processing)
 * - Letta's sleep-time agent (non-blocking memory refinement)
 */

// ============================================================================
// Thought System
// ============================================================================

/** Types of background thoughts */
export type ThoughtType =
  | 'memory_consolidation'   // Organizing and consolidating memories
  | 'skill_optimization'     // Improving existing skills
  | 'proactive_check'        // Checking for pending tasks or changes
  | 'pattern_prediction'     // Predicting user's next action
  | 'self_review'            // Reviewing own performance
  | 'knowledge_gap_detection' // Identifying missing knowledge
  | 'experience_reflection'; // Reflecting on recent experiences

/** Priority of a background thought */
export type ThoughtPriority = 'low' | 'medium' | 'high' | 'urgent';

/** A single thought in the thought queue */
export interface Thought {
  id: string;
  type: ThoughtType;
  priority: ThoughtPriority;
  /** Description of what this thought should do */
  description: string;
  /** Context for the thought */
  context: string;
  /** When this thought was created */
  createdAt: string;
  /** When this thought should execute (for scheduled thoughts) */
  scheduledAt?: string;
  /** Status */
  status: ThoughtStatus;
  /** Result of execution */
  result?: ThoughtResult;
  /** Number of retry attempts */
  retryCount: number;
}

export type ThoughtStatus = 'pending' | 'running' | 'completed' | 'failed' | 'skipped';

/** Result of executing a thought */
export interface ThoughtResult {
  /** What was done */
  action: string;
  /** Key findings */
  findings: string[];
  /** Whether user notification is recommended */
  notifyUser: boolean;
  /** Notification message if applicable */
  notificationMessage?: string;
  /** Any data produced */
  data?: Record<string, unknown>;
}

// ============================================================================
// Proactive Suggestions
// ============================================================================

/** A proactive suggestion generated by background thinking */
export interface ProactiveSuggestion {
  id: string;
  timestamp: string;
  type: SuggestionType;
  title: string;
  description: string;
  confidence: number;
  /** Whether user action is required */
  requiresUserAction: boolean;
  /** Suggested action (if automated) */
  suggestedAction?: string;
  /** Priority */
  priority: ThoughtPriority;
  /** Status */
  status: 'pending' | 'accepted' | 'dismissed' | 'auto_executed';
}

export type SuggestionType =
  | 'task_reminder'        // Remind about pending tasks
  | 'optimization'         // Suggest an optimization
  | 'follow_up'            // Follow up on a previous conversation
  | 'preparation'          // Pre-prepare resources for predicted need
  | 'knowledge_update'     // Suggest updating knowledge
  | 'skill_suggestion';    // Suggest using a learned skill

// ============================================================================
// Proactive Engine Config
// ============================================================================

export interface ProactiveEngineConfig {
  /** How often to run background thinking (in minutes, default: 5) */
  thinkingIntervalMinutes: number;
  /** Maximum concurrent thoughts */
  maxConcurrentThoughts: number;
  /** Maximum thoughts per cycle */
  maxThoughtsPerCycle: number;
  /** Enable automatic execution of low-risk suggestions */
  enableAutoExecution: boolean;
  /** Risk levels that require user confirmation */
  requireConfirmationAboveRisk: 'low' | 'medium' | 'high';
  /** Enable proactive notifications to user */
  enableNotifications: boolean;
}

export function defaultProactiveEngineConfig(): ProactiveEngineConfig {
  return {
    thinkingIntervalMinutes: 5,
    maxConcurrentThoughts: 3,
    maxThoughtsPerCycle: 10,
    enableAutoExecution: false, // Conservative default
    requireConfirmationAboveRisk: 'low',
    enableNotifications: true,
  };
}
